# About
title: Curious Mustard
description: A blog
url: https://curiousmustard.github.io/
author:
    name: Jen Hubbard
    email: curiousmustard@gmail.com
    url: https://curiousmustard.com
github:
  repo:              https://github.com/curiousmustard/strategicwriting

# Dependencies
markdown: kramdown

baseurl:  "/"

# Permalinks
permalink: pretty

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

paginate:         5
